const USERS_FETCHING = "USERS_FETCHING";
const USERS_SUCCESS = "USERS_SUCCESS";
const USERS_FAILED = "USERS_FAILED";
const USER_SELECTED = "USER_SELECTED";
const USER_DELETED = "USER_DELETED";
const CLEAR_USERS_LIST = "CLEAR_USERS_LIST";

export { USERS_FETCHING, USERS_SUCCESS, USERS_FAILED, USER_SELECTED, USER_DELETED, CLEAR_USERS_LIST };
